// Generated by scripts/generate-lucide-icons.js from lucide-static 1.49.0.
// ISC + Feather MIT; notices are embedded and copied to third-party/lucide-license.txt.
using System.Collections.Generic;
using System.Windows.Media;

namespace VisionGuard.Detector.Windows.Icons
{
    public enum LucideGlyph { Check, ChevronDown, ChevronRight, Plus, Trash2 }

    internal static class LucideGeometry
    {
        internal static readonly Dictionary<LucideGlyph, Geometry[]> Paths = new Dictionary<LucideGlyph, Geometry[]>
        {
            [LucideGlyph.Check] = Parse("M20 6 9 17l-5-5"),
            [LucideGlyph.ChevronDown] = Parse("m6 9 6 6 6-6"),
            [LucideGlyph.ChevronRight] = Parse("m9 18 6-6-6-6"),
            [LucideGlyph.Plus] = Parse("M5 12h14", "M12 5v14"),
            [LucideGlyph.Trash2] = Parse("M10 11v6", "M14 11v6", "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6", "M3 6h18", "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"),
        };

        private static Geometry[] Parse(params string[] paths)
        {
            var result = new Geometry[paths.Length];
            for (var i = 0; i < paths.Length; i++) { result[i] = Geometry.Parse(paths[i]); result[i].Freeze(); }
            return result;
        }
    }
}
