<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;net10.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
    <Nullable>disable</Nullable>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../detector/windows-wpf/Net/MinimalWebSocketClient.cs" Link="MinimalWebSocketClient.cs" />
  </ItemGroup>
</Project>
