// Generated by scripts/generate-lucide-icons.js from lucide-static 1.49.0.
// ISC + Feather MIT; notices are bundled in assets/third-party/lucide-license.txt.
package com.xgwnje.visionguard.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

object LucideIcons {
    val Activity: ImageVector by lazy {
        vector("activity", false, listOf(
            "M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2"
        ))
    }

    val ArrowLeft: ImageVector by lazy {
        vector("arrow-left", true, listOf(
            "m12 19-7-7 7-7",
            "M19 12H5"
        ))
    }

    val Bell: ImageVector by lazy {
        vector("bell", false, listOf(
            "M10.268 21a2 2 0 0 0 3.464 0",
            "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"
        ))
    }

    val BellOff: ImageVector by lazy {
        vector("bell-off", false, listOf(
            "M10.268 21a2 2 0 0 0 3.464 0",
            "M17 17H4a1 1 0 0 1-.74-1.673C4.59 13.956 6 12.499 6 8a6 6 0 0 1 .258-1.742",
            "m2 2 20 20",
            "M8.668 3.01A6 6 0 0 1 18 8c0 2.687.77 4.653 1.707 6.05"
        ))
    }

    val BellRing: ImageVector by lazy {
        vector("bell-ring", false, listOf(
            "M10.268 21a2 2 0 0 0 3.464 0",
            "M22 8c0-2.3-.8-4.3-2-6",
            "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326",
            "M4 2C2.8 3.7 2 5.7 2 8"
        ))
    }

    val Bike: ImageVector by lazy {
        vector("bike", false, listOf(
            "M15 17.5a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0Z",
            "M2 17.5a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0Z",
            "M14 5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z",
            "M12 17.5V14l-3-3 4-3 2 3h2"
        ))
    }

    val BusFront: ImageVector by lazy {
        vector("bus-front", false, listOf(
            "M4 6 2 7",
            "M10 6h4",
            "m22 7-2-1",
            "M6 3H18a2 2 0 0 1 2 2V17a2 2 0 0 1 -2 2H6a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2Z",
            "M4 11h16",
            "M8 15h.01",
            "M16 15h.01",
            "M6 19v2",
            "M18 21v-2"
        ))
    }

    val Car: ImageVector by lazy {
        vector("car", false, listOf(
            "M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2",
            "M5 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0Z",
            "M9 17h6",
            "M15 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0Z"
        ))
    }

    val ChevronRight: ImageVector by lazy {
        vector("chevron-right", true, listOf(
            "m9 18 6-6-6-6"
        ))
    }

    val CircleAlert: ImageVector by lazy {
        vector("circle-alert", false, listOf(
            "M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0Z",
            "M12 8L12 12",
            "M12 16L12.01 16"
        ))
    }

    val CircleCheck: ImageVector by lazy {
        vector("circle-check", false, listOf(
            "M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0Z",
            "m16 9-5.5 5.5L8 12"
        ))
    }

    val CircleHelp: ImageVector by lazy {
        vector("circle-help", false, listOf(
            "M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0Z",
            "M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3",
            "M12 17h.01"
        ))
    }

    val CloudOff: ImageVector by lazy {
        vector("cloud-off", false, listOf(
            "M10.94 5.274A7 7 0 0 1 15.71 10h1.79a4.5 4.5 0 0 1 4.222 6.057",
            "M18.796 18.81A4.5 4.5 0 0 1 17.5 19H9A7 7 0 0 1 5.79 5.78",
            "m2 2 20 20"
        ))
    }

    val Download: ImageVector by lazy {
        vector("download", false, listOf(
            "M12 15V3",
            "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4",
            "m7 10 5 5 5-5"
        ))
    }

    val GripHorizontal: ImageVector by lazy {
        vector("grip-horizontal", false, listOf(
            "M11 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z",
            "M18 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z",
            "M4 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z",
            "M11 15a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z",
            "M18 15a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z",
            "M4 15a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z"
        ))
    }

    val ImageOff: ImageVector by lazy {
        vector("image-off", false, listOf(
            "M2 2L22 22",
            "M10.41 10.41a2 2 0 1 1-2.83-2.83",
            "M13.5 13.5L6 21",
            "M18 12L21 15",
            "M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59",
            "M21 15V5a2 2 0 0 0-2-2H9"
        ))
    }

    val Monitor: ImageVector by lazy {
        vector("monitor", false, listOf(
            "M4 3H20a2 2 0 0 1 2 2V15a2 2 0 0 1 -2 2H4a2 2 0 0 1 -2 -2V5a2 2 0 0 1 2 -2Z",
            "M8 21L16 21",
            "M12 17L12 21"
        ))
    }

    val Motorbike: ImageVector by lazy {
        vector("motorbike", false, listOf(
            "m18 14-1-3",
            "m3 9 6 2a2 2 0 0 1 2-2h2a2 2 0 0 1 1.99 1.81",
            "M8 17h3a1 1 0 0 0 1-1 6 6 0 0 1 6-6 1 1 0 0 0 1-1v-.75A5 5 0 0 0 17 5",
            "M16 17a3 3 0 1 0 6 0a3 3 0 1 0 -6 0Z",
            "M2 17a3 3 0 1 0 6 0a3 3 0 1 0 -6 0Z"
        ))
    }

    val Pause: ImageVector by lazy {
        vector("pause", false, listOf(
            "M15 3H18a1 1 0 0 1 1 1V20a1 1 0 0 1 -1 1H15a1 1 0 0 1 -1 -1V4a1 1 0 0 1 1 -1Z",
            "M6 3H9a1 1 0 0 1 1 1V20a1 1 0 0 1 -1 1H6a1 1 0 0 1 -1 -1V4a1 1 0 0 1 1 -1Z"
        ))
    }

    val Pencil: ImageVector by lazy {
        vector("pencil", false, listOf(
            "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z",
            "m15 5 4 4"
        ))
    }

    val Percent: ImageVector by lazy {
        vector("percent", false, listOf(
            "M19 5L5 19",
            "M4 6.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0Z",
            "M15 17.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0Z"
        ))
    }

    val Play: ImageVector by lazy {
        vector("play", false, listOf(
            "M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"
        ))
    }

    val Power: ImageVector by lazy {
        vector("power", false, listOf(
            "M12 2v10",
            "M18.4 6.6a9 9 0 1 1-12.77.04"
        ))
    }

    val RefreshCw: ImageVector by lazy {
        vector("refresh-cw", false, listOf(
            "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8",
            "M21 3v5h-5",
            "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16",
            "M8 16H3v5"
        ))
    }

    val SlidersHorizontal: ImageVector by lazy {
        vector("sliders-horizontal", false, listOf(
            "M10 5H3",
            "M12 19H3",
            "M14 3v4",
            "M16 17v4",
            "M21 12h-9",
            "M21 19h-5",
            "M21 5h-7",
            "M8 10v4",
            "M8 12H3"
        ))
    }

    val Timer: ImageVector by lazy {
        vector("timer", false, listOf(
            "M10 2L14 2",
            "M12 14L15 11",
            "M4 14a8 8 0 1 0 16 0a8 8 0 1 0 -16 0Z"
        ))
    }

    val Trash2: ImageVector by lazy {
        vector("trash-2", false, listOf(
            "M10 11v6",
            "M14 11v6",
            "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6",
            "M3 6h18",
            "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
        ))
    }

    val Truck: ImageVector by lazy {
        vector("truck", false, listOf(
            "M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2",
            "M15 18H9",
            "M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14",
            "M15 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0Z",
            "M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0Z"
        ))
    }

    val UserRound: ImageVector by lazy {
        vector("user-round", false, listOf(
            "M7 8a5 5 0 1 0 10 0a5 5 0 1 0 -10 0Z",
            "M20 21a8 8 0 0 0-16 0"
        ))
    }

    val X: ImageVector by lazy {
        vector("x", false, listOf(
            "M18 6 6 18",
            "m6 6 12 12"
        ))
    }

    private fun vector(name: String, autoMirror: Boolean, paths: List<String>): ImageVector =
        ImageVector.Builder(name = name, defaultWidth = 24.dp, defaultHeight = 24.dp,
            viewportWidth = 24f, viewportHeight = 24f, autoMirror = autoMirror).apply {
            paths.forEach { data ->
                addPath(pathData = PathParser().parsePathString(data).toNodes(), fill = null,
                    stroke = SolidColor(Color.Black), strokeLineWidth = 2f,
                    strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round)
            }
        }.build()
}
